template: testify
packages:
  github.com/talx-hub/gopher-bonus:
    config:
      recursive: true
      all: true
      dir: '{{.InterfaceDir}}/mocks'
      filename: 'mock_{{.InterfaceName}}.go'
      structname: "Mock{{.InterfaceName}}"
      pkgname: mocks
