services:
  database:
    container_name: gophermart-database
    image: postgres:${POSTGRES_TAG}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gophermart -d gophermart"]
      interval: 5s
      retries: 3
      timeout: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "P@ssw0rd"
      POSTGRES_DB: postgres
      POSTGRES_DATA: "/var/lib/postgresql/data"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "gophermart-volume:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - gophermart-network
    restart: always

volumes:
  gophermart-volume:
    name: gophermart-volume

networks:
  gophermart-network:
    driver: bridge
    name: gophermart-network
