// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accrual struct {
	IDAcc      int32
	IDAccOrder int32
	Amount     pgtype.Numeric
}

type AccruedOrder struct {
	IDAccOrder int32
	IDUser     int32
	OrderNo    string
	UploadedAt pgtype.Timestamptz
	IDStatus   int32
}

type PasswordHash struct {
	IDPassword   int32
	IDUser       int32
	HashPassword string
}

type Status struct {
	IDStatus   int32
	NameStatus string
}

type UserHash struct {
	IDUser    int32
	HashLogin string
}

type Withdraw struct {
	IDWithdraw       int32
	IDWithdrawnOrder pgtype.Int4
	Amount           pgtype.Numeric
}

type WithdrawnOrder struct {
	IDWithdrawnOrder int32
	IDUser           int32
	OrderNo          string
	ProcessedAt      pgtype.Timestamptz
	IDStatus         int32
}
