// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccruedOrder struct {
	IDAccOrder int32
	IDUser     string
	NameOrder  string
	UploadedAt pgtype.Timestamptz
	IDStatus   int32
	Amount     pgtype.Numeric
}

type PasswordHash struct {
	IDPassword   int32
	IDUser       string
	HashPassword string
}

type Status struct {
	IDStatus   int32
	NameStatus string
}

type UserHash struct {
	IDUser    string
	HashLogin string
}

type WithdrawnOrder struct {
	IDWithdrawnOrder int32
	IDUser           string
	NameOrder        string
	ProcessedAt      pgtype.Timestamptz
	Amount           pgtype.Numeric
}
